import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import importPlugin from "eslint-plugin-import";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      "**/*.config.js",
      "**/*.config.mjs",
      // Generated by Next.js on every build; not ours to lint or edit.
      "**/next-env.d.ts",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,

  {
    rules: {
      // The typescript rule says: no `any`, no silencing casts, no non-null assertions.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector: "TSAsExpression[typeAnnotation.typeName.name!='const']",
          message:
            "Casts hide type errors. Narrow with a runtime check instead; see .claude/rules/typescript.md.",
        },
      ],
    },
  },

  // Workspace boundary: the two apps must not reach into each other, however the
  // import is spelled. `no-restricted-imports` only matches the literal specifier,
  // so a relative escape like "../../api/src/x" slips past it — `no-restricted-paths`
  // resolves the path and catches both forms.
  {
    files: ["apps/**/*.{ts,tsx}", "packages/**/*.{ts,tsx}"],
    plugins: { import: importPlugin },
    settings: {
      // Without a TypeScript-aware resolver the path rule resolves nothing and
      // passes everything silently, which is worse than not having it.
      "import/resolver": {
        typescript: { project: ["apps/*/tsconfig.json", "packages/*/tsconfig.json"] },
      },
    },
    rules: {
      "import/no-restricted-paths": [
        "error",
        {
          zones: [
            {
              target: "./apps/web",
              from: "./apps/api",
              message:
                "apps/web must not import from apps/api. Put shared contract types in packages/shared.",
            },
            {
              target: "./apps/api",
              from: "./apps/web",
              message:
                "apps/api must not import from apps/web. Put shared contract types in packages/shared.",
            },
            {
              target: "./packages",
              from: "./apps",
              message: "packages/* must not depend on an app; the dependency runs the other way.",
            },
          ],
        },
      ],
      // The package-name form of the same mistake.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@data-room/api", "@data-room/api/**", "@data-room/web", "@data-room/web/**"],
              message:
                "The apps must not import each other. Put shared contract types in packages/shared.",
            },
          ],
        },
      ],
    },
  },

  // Only the storage module may talk to the provider SDK directly.
  {
    files: ["apps/api/src/**/*.ts"],
    ignores: ["apps/api/src/storage/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@supabase/supabase-js",
              message:
                "Only apps/api/src/storage may use the provider SDK; go through StorageService.",
            },
          ],
        },
      ],
    },
  },

  // Build scripts run on Node, outside any workspace's tsconfig.
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: { console: "readonly", process: "readonly", URL: "readonly", fetch: "readonly" },
    },
  },

  // Cypress custom commands can only be typed by merging into its global Chainable
  // interface. A `type` cannot be merged and there is no ES-module way to augment a global
  // namespace, so these two rules genuinely do not apply here. Scoped to support files
  // only — application code stays under the general rule.
  {
    files: ["**/cypress/support/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-namespace": "off",
      "@typescript-eslint/consistent-type-definitions": "off",
    },
  },

  // Tests may be looser about casts, but not about `any`.
  {
    files: ["**/*.spec.ts", "**/*.spec.tsx", "**/*.cy.ts", "**/*.cy.tsx", "**/cypress/**"],
    rules: {
      "no-restricted-syntax": "off",
    },
  },
);
